controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
ai_interview:
    resource: '../src/Controller/AiInterviewController.php'
    type: annotation
