# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  avatars_directory: '%kernel.project_dir%/public/uploads/avatars'
  profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile-pictures'
  jitsi_domain: '%env(JITSI_DOMAIN)%'
  jitsi_room_prefix: '%env(JITSI_ROOM_PREFIX)%'
  azure_face_endpoint: '%env(AZURE_FACE_ENDPOINT)%'
  azure_face_key: '%env(AZURE_FACE_KEY)%'
  app.aws.region: '%env(AWS_REGION)%'
  app.aws.bucket: '%env(AWS_BUCKET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
  # Explicit configuration for AiCodeEvaluatorService
    App\Service\AiCodeEvaluatorService:
      arguments:
        $aiApiBaseUrl: '%env(AI_EVALUATOR_URL)%'

  # Explicit configuration for MissionAnalyzerService
    App\Service\MissionAnalyzerService:
      arguments:
        $aiApiBaseUrl: '%env(AI_EVALUATOR_URL)%'

  # Email Service Configuration
    App\Service\EmailService:
      arguments:
        $senderEmail: '%env(MAILER_SENDER_EMAIL)%'
        $senderName: '%env(MAILER_SENDER_NAME)%'
        $gmailPassword: '%env(GMAIL_APP_PASSWORD)%'
        $logger: '@logger'

  # Jitsi Service
    App\Service\JitsiLinkGenerator:
      arguments:
        $params: '@parameter_bag'

    App\Service\PaiementService:
      arguments:
        $stripeSecretKey: '%env(STRIPE_SECRET_KEY)%'
        $stripePublicKey: '%env(STRIPE_PUBLIC_KEY)%'


    App\Service\SmsService:
      arguments:
        $twilioSid: '%env(TWILIO_SID)%'
        $twilioAuthToken: '%env(TWILIO_AUTH_TOKEN)%'
        $twilioPhoneNumber: '%env(TWILIO_PHONE_NUMBER)%'


    App\Service\S3Service:
      arguments:
        $region: '%app.aws.region%'
        $bucket: '%app.aws.bucket%'
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones